version: '2'
services:
    moment-app:
        image: moment
        external_links:
            - moment-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/moment?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    moment-mysql:
        extends:
            file: mysql.yml
            service: moment-mysql
